# Generated by Django 3.2.8 on 2021-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessagecron',
            name='database_title',
            field=models.CharField(blank=True, help_text='This title is mail representation in database\n leave blank if database title should be taken from title', max_length=100),
        ),
        migrations.AddField(
            model_name='emailmessagemembershiptime',
            name='database_title',
            field=models.CharField(blank=True, help_text='This title is mail representation in database\n leave blank if database title should be taken from title', max_length=100),
        ),
        migrations.AddField(
            model_name='emailmessagetodate',
            name='database_title',
            field=models.CharField(blank=True, help_text='This title is mail representation in database\n leave blank if database title should be taken from title', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmessagecron',
            name='title',
            field=models.CharField(help_text='This is mail title', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmessagemembershiptime',
            name='title',
            field=models.CharField(help_text='This is mail title', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmessagetodate',
            name='title',
            field=models.CharField(help_text='This is mail title', max_length=100),
        ),
    ]
