# Generated by Django 3.2.8 on 2021-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_newsletter', '0002_auto_20211113_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessagecron',
            name='database_title',
            field=models.CharField(blank=True, help_text='This title is mail representation in database leave blank if database title should be taken from title', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmessagemembershiptime',
            name='database_title',
            field=models.CharField(blank=True, help_text='This title is mail representation in database leave blank if database title should be taken from title', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmessagetodate',
            name='database_title',
            field=models.CharField(blank=True, help_text='This title is mail representation in database leave blank if database title should be taken from title', max_length=100),
        ),
    ]
