# Generated by Django 3.2.8 on 2021-11-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_newsletter', '0003_auto_20211113_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='previous_confirmed_state',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
    ]
