# Generated by Django 3.2.8 on 2021-11-13 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_newsletter', '0005_auto_20211113_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
