# Generated by Django 3.2.8 on 2021-11-14 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_newsletter', '0006_alter_member_join_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_datetime',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
