# Generated by Django 3.2.8 on 2021-11-19 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_newsletter', '0007_alter_member_join_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
